---
title: "A minimal flipbook"
subtitle: "With flipbookr and xaringan"
author: "You!"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
library(latex2exp)
library(ggpattern)
library(ggpubr)
library(sp)

poly <- tribble(
  ~x, ~y, ~holes, ~id,
  0.1802,0.8712, 1L, 1L,
  0.2573,0.7795, 1L, 2L,
  0.0331,0.6281, 1L, 3L,
  0.2457,0.6223, 1L, 4L,
  0.2806,0.5088, 1L, 5L,
  0.3723,0.6136, 1L, 6L,
  0.3621,0.3996, 1L, 7L,
  0.4306,0.3297, 1L, 8L,
  0.5266,0.3195, 1L, 9L,
  0.5630,0.0677, 1L, 10L,
  0.8629,0.2103, 1L, 11L,
  0.9401,0.5189, 1L, 12L,
  0.7086,0.4942, 1L, 13L,
  0.5892,0.6529, 1L, 14L,
  0.6693,0.8014, 1L, 15L,
  0.3985,0.9382, 1L, 16L,
  0.6000,0.4000, 2L, 17L,
  0.6000,0.2000, 2L, 18L,
  0.8000,0.2000, 2L, 19L,
  0.8000,0.4000, 2L, 20L
)

poly_plein <- tribble(
  ~x, ~y, ~holes, ~id,
  0.1802,0.8712, 1L, 1L,
  0.2573,0.7795, 1L, 2L,
  0.0331,0.6281, 1L, 3L,
  0.2457,0.6223, 1L, 4L,
  0.2806,0.5088, 1L, 5L,
  0.3723,0.6136, 1L, 6L,
  0.3621,0.3996, 1L, 7L,
  0.4306,0.3297, 1L, 8L,
  0.5266,0.3195, 1L, 9L,
  0.5630,0.0677, 1L, 10L,
  0.8629,0.2103, 1L, 11L,
  0.9401,0.5189, 1L, 12L,
  0.7086,0.4942, 1L, 13L,
  0.5892,0.6529, 1L, 14L,
  0.6693,0.8014, 1L, 15L,
  0.3985,0.9382, 1L, 16L
)

poly_trou <- tribble(
  ~x, ~y, ~holes, ~id,
  0.6000,0.4000, 2L, 17L,
  0.6000,0.2000, 2L, 18L,
  0.8000,0.2000, 2L, 19L,
  0.8000,0.4000, 2L, 20L
)

poly_small <- tribble(
  ~x, ~y,
  0.84578829, 0.22430933,
  0.91374870, 0.49597492,
  0.69943962, 0.47310911,
  0.56551379, 0.65111605,
  0.64194392, 0.79281236,
  0.39666975, 0.91671748,
  0.21495193, 0.86094518,
  0.28690924, 0.77536172,
  0.09592715, 0.64639344,
  0.26059704, 0.64190103,
  0.28917259, 0.54896909,
  0.36660303, 0.63746102,
  0.39295365, 0.62683747,
  0.38249282, 0.40736516,
  0.43985652, 0.34882907,
  0.54417031, 0.33774573,
  0.57891272, 0.09741218,
  0.75260197, 0.18000000,
  0.58000000, 0.18000000,
  0.58000000, 0.42000000,
  0.82000000, 0.42000000,
  0.82000000, 0.21204721,
)

c_poly_plein <- poly_plein %>% 
  slice(chull(x,y))

b1 <- poly[c(1:3),]
b3 <- poly[c(3:10),]
b2 <- poly[c(12,13,14,15),]

c1 <- poly[c(4,5,6),]
c2 <- poly[c(6,7,8,9),]

c_b3 <- b3 %>% 
  slice(chull(x,y))

delta <- 0.02
xmin <- 0
xmax <- 1
ymin <- 0
ymax <- 1
mygrid <- as_tibble(expand.grid(x = seq(xmin,xmax,delta), y = seq(ymin,ymax,delta)))
mygrid <- mygrid %>% 
        mutate(
                xbl = x - delta/2,
                ybl = y - delta/2,
                xbr = x + delta/2,
                ybr = y - delta/2,
                xtl = x - delta/2,
                ytl = y + delta/2,
                xtr = x + delta/2,
                ytr = y + delta/2,
        )

mygrid <- mygrid %>% 
        mutate(
                inblp1 = point.in.polygon(mygrid$xbl,mygrid$ybl,poly_plein$x,poly_plein$y),
                inbrp1 = point.in.polygon(mygrid$xbr,mygrid$ybr,poly_plein$x,poly_plein$y),
                intlp1 = point.in.polygon(mygrid$xtl,mygrid$ytl,poly_plein$x,poly_plein$y),
                intrp1 = point.in.polygon(mygrid$xtr,mygrid$ytr,poly_plein$x,poly_plein$y),
                inblp2 = point.in.polygon(mygrid$xbl,mygrid$ybl,poly_trou$x,poly_trou$y),
                inbrp2 = point.in.polygon(mygrid$xbr,mygrid$ybr,poly_trou$x,poly_trou$y),
                intlp2 = point.in.polygon(mygrid$xtl,mygrid$ytl,poly_trou$x,poly_trou$y),
                intrp2 = point.in.polygon(mygrid$xtr,mygrid$ytr,poly_trou$x,poly_trou$y),
                in_out = (inblp1 & !inblp2) & (inbrp1 & !inbrp2) & (intlp1 & !intlp2) & (intrp1 & !intrp2)
        )
```
---
class: center, middle

`r chunk_reveal("my_cars",break_type = "user", display_type = "output")`

```{r my_cars, include = FALSE}
ggplot() +
  geom_tile(data = mygrid,aes(x=x,y=y,fill=in_out), colour = 'gray90')+
  scale_fill_manual(breaks = c(FALSE, TRUE), 
                  values=c("white", "green"))+
  geom_polygon(
    data=poly,
    aes(x=x,y=y,subgroup=holes),
    fill = "#3b528b",
    color = "black", 
    alpha = 0,
    size=1
    )+
  geom_point(data=poly,aes(x=x,y=y,), size=3)+
  theme_void()+
  theme(legend.position="none")+ 
  geom_segment(aes(x=0,y=0,xend=1,yend=0), colour="black")+
  geom_segment(aes(x=0,y=1,xend=1,yend=1), colour="black")+ 
  geom_segment(aes(x=0,y=0,xend=0,yend=1), colour="black")+ 
  geom_segment(aes(x=1,y=0,xend=1,yend=1), colour="black")+ #BREAK
  geom_segment(aes(x=0,y=0.5,xend=1,yend=0.5), colour="blue", size=2)+ #BREAK
  geom_segment(aes(x=0.5,y=0,xend=0.5,yend=1), colour="blue", size=2)+ #BREAK
  geom_segment(aes(x=0.25,y=0.5,xend=0.25,yend=1), colour="red", size=1.5)+ #BREAK
  geom_segment(aes(x=0,y=0.75,xend=0.5,yend=0.75), colour="red", size=1.5)
```

